version: 1.0.{build}
image: Visual Studio 2013

platform:
  - x64

build:
  steps:
    - checkout
    - vs2013:
        solution: x64dbg.sln
        configuration: Release
        platform: x64
        build_arguments: /p:PlatformToolset=v120
